---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

# here are some plots

today we're making interactive plots in plotly. we'll make examples using the NYC airbnb dataset.

```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

do some initial data cleaning/subsetting.

```{r}
data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(rating = review_scores_location / 2) |>
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) |>
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
```

use plotly to make some quick plots.

```{r}
nyc_airbnb |> 
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) |> 
  plot_ly(
    x = ~lat, y = ~long, color = ~price,
    type = "scatter", mode = "markers", alpha = 0.5
  )
```

```{r}
nyc_airbnb |> 
   mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
   plot_ly(
     y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")
```

let's do a bar chart with number of rentals.

```{r}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
  plot_ly(
    x = ~neighbourhood, y = ~n, 
    type = "bar")
```

```{r}
plot_ly(
  z = volcano, type = "heatmap"
)
```











